services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    profiles: ['prod', 'dev']

  server:
    build:
      context: ./
      target: ${NODE_ENV:-production}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT:-5000}:${PORT:-5000}'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    profiles: ['prod', 'dev']

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy
    restart: unless-stopped
    profiles: ['prod', 'dev']

  # postgres:
  #   image: postgres:17-alpine
  #   container_name: postgres_backup
  #   environment:
  #     POSTGRES_USER: ${PBW_POSTGRES_USER}
  #     POSTGRES_DB: ${PBW_POSTGRES_DB}
  #     POSTGRES_PASSWORD: ${PBW_POSTGRES_PASSWORD}
  #   ports:
  #     - '5432'
  #   volumes:
  #     - data-postgres-backup:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   profiles: ['prod']

  # pgbackweb:
  #   image: eduardolat/pgbackweb:latest
  #   container_name: pgbackweb
  #   ports:
  #     - '8085:8085' # Access the web interface at http://localhost:8085
  #   volumes:
  #     - ./backups:/backups # If you only use S3 destinations, you don't need this volume
  #   environment:
  #     PBW_ENCRYPTION_KEY: ${PBW_ENCRYPTION_KEY} # Change this to a strong key
  #     PBW_POSTGRES_CONN_STRING: 'postgresql://${PBW_POSTGRES_USER}:${PBW_POSTGRES_PASSWORD}@postgres:5432/${PBW_POSTGRES_DB}?sslmode=disable'
  #     TZ: 'Africa/Tunis' # Set your timezone, optional
  #   networks:
  #     - default
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   profiles: ['prod']

volumes:
  postgres_data:
  pgadmin_data:
